// GENERATED by @edgedb/generate v0.0.7
// Run 'npx @edgedb/generate edgeql-js' to re-generate

import * as $ from "../reflection";
import * as _ from "../imports";
import type * as _std from "./std";
export declare type $EventλShape = $.typeutil.flatten<_std.$Object_0d79ae1a7ccc11edbb9609e32e1f36efλShape & {
  "tab": $.LinkDesc<$Tab, $.Cardinality.AtMostOne, {}, false, false,  false, false>;
  "user": $.LinkDesc<$User, $.Cardinality.One, {}, false, false,  false, false>;
  "enter_time": $.PropertyDesc<_std.$datetime, $.Cardinality.One, false, false, false, false>;
}>;
declare type $Event = $.ObjectType<"default::Event", $EventλShape, null, [
  ..._std.$Object_0d79ae1a7ccc11edbb9609e32e1f36ef['__exclusives__'],
]>;
declare const $Event: $Event

declare const Event: $.$expr_PathNode<$.TypeSet<$Event, $.Cardinality.Many>, null> 

export declare type $TabλShape = $.typeutil.flatten<_std.$Object_0d79ae1a7ccc11edbb9609e32e1f36efλShape & {
  "active": $.PropertyDesc<_std.$bool, $.Cardinality.One, false, false, false, false>;
  "title": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "url": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "<tab[is Event]": $.LinkDesc<$Event, $.Cardinality.Many, {}, false, false,  false, false>;
  "<tab": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
declare type $Tab = $.ObjectType<"default::Tab", $TabλShape, null, [
  ..._std.$Object_0d79ae1a7ccc11edbb9609e32e1f36ef['__exclusives__'],
]>;
declare const $Tab: $Tab

declare const Tab: $.$expr_PathNode<$.TypeSet<$Tab, $.Cardinality.Many>, null> 

export declare type $UserλShape = $.typeutil.flatten<_std.$Object_0d79ae1a7ccc11edbb9609e32e1f36efλShape & {
  "user_id": $.PropertyDesc<_std.$str, $.Cardinality.One, true, false, false, false>;
  "<user[is Event]": $.LinkDesc<$Event, $.Cardinality.Many, {}, false, false,  false, false>;
  "<user": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
declare type $User = $.ObjectType<"default::User", $UserλShape, null, [
  ..._std.$Object_0d79ae1a7ccc11edbb9609e32e1f36ef['__exclusives__'],
  {user_id: {__element__: _std.$str, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },},
]>;
declare const $User: $User

declare const User: $.$expr_PathNode<$.TypeSet<$User, $.Cardinality.Many>, null> 



export { $Event, Event, $Tab, Tab, $User, User };

declare type __defaultExports = {
  "Event": typeof Event;
  "Tab": typeof Tab;
  "User": typeof User
};
declare const __defaultExports: __defaultExports;
export default __defaultExports;
