// GENERATED by @edgedb/generate v0.0.7
// Run 'npx @edgedb/generate edgeql-js' to re-generate

import * as $ from "../reflection.mjs";
import * as _ from "../imports.mjs";
const $Event = $.makeType(_.spec, "1b543772-89af-11ed-828d-9d3b76b19aba", _.syntax.literal);

const Event= _.syntax.$PathNode($.$toSet($Event, $.Cardinality.Many), null);

const $Tab = $.makeType(_.spec, "1b51fe26-89af-11ed-9347-2df859ef5929", _.syntax.literal);

const Tab= _.syntax.$PathNode($.$toSet($Tab, $.Cardinality.Many), null);

const $User = $.makeType(_.spec, "1b5351a4-89af-11ed-ba53-4de1e7175a83", _.syntax.literal);

const User= _.syntax.$PathNode($.$toSet($User, $.Cardinality.Many), null);



export { $Event, Event, $Tab, Tab, $User, User };

const __defaultExports = {
  "Event": Event,
  "Tab": Tab,
  "User": User
};
export default __defaultExports;
