// GENERATED by @edgedb/generate v0.0.7
// Run 'npx @edgedb/generate edgeql-js' to re-generate

import * as $ from "../reflection.mjs";
import * as _ from "../imports.mjs";
const AccessKind = $.makeType(_.spec, "0db935b2-7ccc-11ed-8fac-71bb6d068ea8", _.syntax.literal);

const AccessPolicyAction = $.makeType(_.spec, "0db8d824-7ccc-11ed-b3ef-4f18b517a607", _.syntax.literal);

const Cardinality = $.makeType(_.spec, "0db64712-7ccc-11ed-b952-054a247ee76d", _.syntax.literal);

const OperatorKind = $.makeType(_.spec, "0db75be8-7ccc-11ed-96ff-8d8c173e57c1", _.syntax.literal);

const ParameterKind = $.makeType(_.spec, "0db8215e-7ccc-11ed-92b7-af3131d60cc6", _.syntax.literal);

const SourceDeleteAction = $.makeType(_.spec, "0db70184-7ccc-11ed-86e3-d7bd935d2d17", _.syntax.literal);

const TargetDeleteAction = $.makeType(_.spec, "0db6a522-7ccc-11ed-af16-79e231cae743", _.syntax.literal);

const TypeModifier = $.makeType(_.spec, "0db87d8e-7ccc-11ed-9f13-b50edd046a17", _.syntax.literal);

const Volatility = $.makeType(_.spec, "0db7c628-7ccc-11ed-937c-2998a1db6524", _.syntax.literal);

const $Object_0db9a7687ccc11ed9ee685408c9df36c = $.makeType(_.spec, "0db9a768-7ccc-11ed-9ee6-85408c9df36c", _.syntax.literal);

const Object_0db9a7687ccc11ed9ee685408c9df36c= _.syntax.$PathNode($.$toSet($Object_0db9a7687ccc11ed9ee685408c9df36c, $.Cardinality.Many), null);

const $SubclassableObject = $.makeType(_.spec, "0dbf6176-7ccc-11ed-b2f7-b10569998e55", _.syntax.literal);

const SubclassableObject= _.syntax.$PathNode($.$toSet($SubclassableObject, $.Cardinality.Many), null);

const $InheritingObject = $.makeType(_.spec, "0e6cd6da-7ccc-11ed-a2a5-6b4c69fa9c5c", _.syntax.literal);

const InheritingObject= _.syntax.$PathNode($.$toSet($InheritingObject, $.Cardinality.Many), null);

const $AnnotationSubject = $.makeType(_.spec, "0e57b67e-7ccc-11ed-aae5-9b4e911fca41", _.syntax.literal);

const AnnotationSubject= _.syntax.$PathNode($.$toSet($AnnotationSubject, $.Cardinality.Many), null);

const $AccessPolicy = $.makeType(_.spec, "0f04f122-7ccc-11ed-9c26-af515f811488", _.syntax.literal);

const AccessPolicy= _.syntax.$PathNode($.$toSet($AccessPolicy, $.Cardinality.Many), null);

const $Alias = $.makeType(_.spec, "0f1f2d62-7ccc-11ed-bc27-7792582b5f0b", _.syntax.literal);

const Alias= _.syntax.$PathNode($.$toSet($Alias, $.Cardinality.Many), null);

const $Annotation = $.makeType(_.spec, "0e5e5b50-7ccc-11ed-ae4e-2f8f6c1cb3f0", _.syntax.literal);

const Annotation= _.syntax.$PathNode($.$toSet($Annotation, $.Cardinality.Many), null);

const $Type = $.makeType(_.spec, "0dc831ac-7ccc-11ed-b085-214221b2ad9b", _.syntax.literal);

const Type= _.syntax.$PathNode($.$toSet($Type, $.Cardinality.Many), null);

const $PrimitiveType = $.makeType(_.spec, "0e06cc46-7ccc-11ed-bc4a-3d0f92cf49b9", _.syntax.literal);

const PrimitiveType= _.syntax.$PathNode($.$toSet($PrimitiveType, $.Cardinality.Many), null);

const $CollectionType = $.makeType(_.spec, "0e120926-7ccc-11ed-9414-11b331b85b2b", _.syntax.literal);

const CollectionType= _.syntax.$PathNode($.$toSet($CollectionType, $.Cardinality.Many), null);

const $Array = $.makeType(_.spec, "0e1d9ea8-7ccc-11ed-a44e-afb51c37fc11", _.syntax.literal);

const Array= _.syntax.$PathNode($.$toSet($Array, $.Cardinality.Many), null);

const $CallableObject = $.makeType(_.spec, "0e8653b2-7ccc-11ed-97b8-519bc3579bc5", _.syntax.literal);

const CallableObject= _.syntax.$PathNode($.$toSet($CallableObject, $.Cardinality.Many), null);

const $VolatilitySubject = $.makeType(_.spec, "0e95b8f2-7ccc-11ed-bef3-8f6f5ac23f69", _.syntax.literal);

const VolatilitySubject= _.syntax.$PathNode($.$toSet($VolatilitySubject, $.Cardinality.Many), null);

const $Cast = $.makeType(_.spec, "10a5a1de-7ccc-11ed-a3b4-bb86ebadcbfa", _.syntax.literal);

const Cast= _.syntax.$PathNode($.$toSet($Cast, $.Cardinality.Many), null);

const $ConsistencySubject = $.makeType(_.spec, "0eb940b0-7ccc-11ed-8438-93996d99b800", _.syntax.literal);

const ConsistencySubject= _.syntax.$PathNode($.$toSet($ConsistencySubject, $.Cardinality.Many), null);

const $Constraint = $.makeType(_.spec, "0e9d6408-7ccc-11ed-b372-15639ce43ba2", _.syntax.literal);

const Constraint= _.syntax.$PathNode($.$toSet($Constraint, $.Cardinality.Many), null);

const $Delta = $.makeType(_.spec, "0e4f812a-7ccc-11ed-a6b8-5316e6ea78f8", _.syntax.literal);

const Delta= _.syntax.$PathNode($.$toSet($Delta, $.Cardinality.Many), null);

const $Extension = $.makeType(_.spec, "10cdeaf4-7ccc-11ed-a677-c9b58e844525", _.syntax.literal);

const Extension= _.syntax.$PathNode($.$toSet($Extension, $.Cardinality.Many), null);

const $Function = $.makeType(_.spec, "10745232-7ccc-11ed-a73b-67ed9300be74", _.syntax.literal);

const Function= _.syntax.$PathNode($.$toSet($Function, $.Cardinality.Many), null);

const $FutureBehavior = $.makeType(_.spec, "10de0628-7ccc-11ed-a2e2-d54ce3056c23", _.syntax.literal);

const FutureBehavior= _.syntax.$PathNode($.$toSet($FutureBehavior, $.Cardinality.Many), null);

const $Global = $.makeType(_.spec, "1060b2cc-7ccc-11ed-8d60-07d1ad5b1b30", _.syntax.literal);

const Global= _.syntax.$PathNode($.$toSet($Global, $.Cardinality.Many), null);

const $Index = $.makeType(_.spec, "0ec6ce24-7ccc-11ed-a1fb-7be2712d1540", _.syntax.literal);

const Index= _.syntax.$PathNode($.$toSet($Index, $.Cardinality.Many), null);

const $Pointer = $.makeType(_.spec, "0ee81fca-7ccc-11ed-a95b-f963470bd42d", _.syntax.literal);

const Pointer= _.syntax.$PathNode($.$toSet($Pointer, $.Cardinality.Many), null);

const $Source = $.makeType(_.spec, "0edc33cc-7ccc-11ed-aad4-ab3f605e6001", _.syntax.literal);

const Source= _.syntax.$PathNode($.$toSet($Source, $.Cardinality.Many), null);

const $Link = $.makeType(_.spec, "0fcffc64-7ccc-11ed-9cd9-754f02beb01a", _.syntax.literal);

const Link= _.syntax.$PathNode($.$toSet($Link, $.Cardinality.Many), null);

const $Migration = $.makeType(_.spec, "10bb9e44-7ccc-11ed-bf63-eb1528bd8581", _.syntax.literal);

const Migration= _.syntax.$PathNode($.$toSet($Migration, $.Cardinality.Many), null);

const $Module = $.makeType(_.spec, "0de1987c-7ccc-11ed-b952-ff2e1d8676fa", _.syntax.literal);

const Module= _.syntax.$PathNode($.$toSet($Module, $.Cardinality.Many), null);

const $ObjectType = $.makeType(_.spec, "0f4f8980-7ccc-11ed-99df-19f8996037d3", _.syntax.literal);

const ObjectType= _.syntax.$PathNode($.$toSet($ObjectType, $.Cardinality.Many), null);

const $Operator = $.makeType(_.spec, "108de2d8-7ccc-11ed-ba6c-c513a22c24c0", _.syntax.literal);

const Operator= _.syntax.$PathNode($.$toSet($Operator, $.Cardinality.Many), null);

const $Parameter = $.makeType(_.spec, "0e7bad5e-7ccc-11ed-b639-a91d3b37fa44", _.syntax.literal);

const Parameter= _.syntax.$PathNode($.$toSet($Parameter, $.Cardinality.Many), null);

const $Property = $.makeType(_.spec, "0ffc16aa-7ccc-11ed-8c29-1f68df7edb3b", _.syntax.literal);

const Property= _.syntax.$PathNode($.$toSet($Property, $.Cardinality.Many), null);

const $PseudoType = $.makeType(_.spec, "0dd114fc-7ccc-11ed-8379-f7896738b024", _.syntax.literal);

const PseudoType= _.syntax.$PathNode($.$toSet($PseudoType, $.Cardinality.Many), null);

const $Range = $.makeType(_.spec, "0e418214-7ccc-11ed-b214-255e886fa3da", _.syntax.literal);

const Range= _.syntax.$PathNode($.$toSet($Range, $.Cardinality.Many), null);

const $ScalarType = $.makeType(_.spec, "0f2da8ce-7ccc-11ed-af81-7beb55830106", _.syntax.literal);

const ScalarType= _.syntax.$PathNode($.$toSet($ScalarType, $.Cardinality.Many), null);

const $Tuple = $.makeType(_.spec, "0e31595c-7ccc-11ed-b483-7de70e94dd28", _.syntax.literal);

const Tuple= _.syntax.$PathNode($.$toSet($Tuple, $.Cardinality.Many), null);

const $TupleElement = $.makeType(_.spec, "0e2c199c-7ccc-11ed-9e77-a5a78ab8561e", _.syntax.literal);

const TupleElement= _.syntax.$PathNode($.$toSet($TupleElement, $.Cardinality.Many), null);



export { AccessKind, AccessPolicyAction, Cardinality, OperatorKind, ParameterKind, SourceDeleteAction, TargetDeleteAction, TypeModifier, Volatility, $Object_0db9a7687ccc11ed9ee685408c9df36c, Object_0db9a7687ccc11ed9ee685408c9df36c, $SubclassableObject, SubclassableObject, $InheritingObject, InheritingObject, $AnnotationSubject, AnnotationSubject, $AccessPolicy, AccessPolicy, $Alias, Alias, $Annotation, Annotation, $Type, Type, $PrimitiveType, PrimitiveType, $CollectionType, CollectionType, $Array, Array, $CallableObject, CallableObject, $VolatilitySubject, VolatilitySubject, $Cast, Cast, $ConsistencySubject, ConsistencySubject, $Constraint, Constraint, $Delta, Delta, $Extension, Extension, $Function, Function, $FutureBehavior, FutureBehavior, $Global, Global, $Index, Index, $Pointer, Pointer, $Source, Source, $Link, Link, $Migration, Migration, $Module, Module, $ObjectType, ObjectType, $Operator, Operator, $Parameter, Parameter, $Property, Property, $PseudoType, PseudoType, $Range, Range, $ScalarType, ScalarType, $Tuple, Tuple, $TupleElement, TupleElement };

const __defaultExports = {
  "AccessKind": AccessKind,
  "AccessPolicyAction": AccessPolicyAction,
  "Cardinality": Cardinality,
  "OperatorKind": OperatorKind,
  "ParameterKind": ParameterKind,
  "SourceDeleteAction": SourceDeleteAction,
  "TargetDeleteAction": TargetDeleteAction,
  "TypeModifier": TypeModifier,
  "Volatility": Volatility,
  "Object": Object_0db9a7687ccc11ed9ee685408c9df36c,
  "SubclassableObject": SubclassableObject,
  "InheritingObject": InheritingObject,
  "AnnotationSubject": AnnotationSubject,
  "AccessPolicy": AccessPolicy,
  "Alias": Alias,
  "Annotation": Annotation,
  "Type": Type,
  "PrimitiveType": PrimitiveType,
  "CollectionType": CollectionType,
  "Array": Array,
  "CallableObject": CallableObject,
  "VolatilitySubject": VolatilitySubject,
  "Cast": Cast,
  "ConsistencySubject": ConsistencySubject,
  "Constraint": Constraint,
  "Delta": Delta,
  "Extension": Extension,
  "Function": Function,
  "FutureBehavior": FutureBehavior,
  "Global": Global,
  "Index": Index,
  "Pointer": Pointer,
  "Source": Source,
  "Link": Link,
  "Migration": Migration,
  "Module": Module,
  "ObjectType": ObjectType,
  "Operator": Operator,
  "Parameter": Parameter,
  "Property": Property,
  "PseudoType": PseudoType,
  "Range": Range,
  "ScalarType": ScalarType,
  "Tuple": Tuple,
  "TupleElement": TupleElement
};
export default __defaultExports;
